all: plots
plots:
	gnuplot signal_frequency_plot_code
	gnuplot signal_time_plot_code
	
	gnuplot sinus_time_plot_code
	gnuplot clear_sinus_time_plot_code
	gnuplot sinus_frequency_plot_code
	gnuplot sinus_clear_frequency_plot_code
	gnuplot sinus_time_after_plot_code